WHITELISTED_REGEX_STR = [
    r"\d+",
    r"Key type .* registered",
    r"NODE_DATA\(\d+\) allocated \[mem HEX-HEX\]",
    r"SRAT: PXM \d+ \-> APIC HEX \-> Node \d+",
    r"ata\d+: SATA link down \(SStatus \d+ SControl \d+\)",
    r"ata\d+: SATA max UDMA/\d+ abar m\d+@HEX port HEX irq",
    r"ata\d+: DUMMY",
    r"gran_size: \d+.*chunk_size: \d+.*num_reg: \d+.*lose cover RAM: \d+.*",
    r"hub [\d\-\.]+:[\d\-\.]+: USB hub found",
    r"hub [\d\-\.]+:[\d\-\.]+: \d+ ports detected",
    r"mlx5_core ADDR .*: renamed from .*",
    r"mlx5_core ADDR: [\d\.]+ Gb/s available PCIe bandwidth .* x16 link\)",
    r"mpt3sas_cm[0-7]: .*",
    r"pci ADDR: .*",
    r"systemd\[1\]: (Starting|Started|Reached|Queued|Listening on| Mounted|Created|Finished|Mounting|Mounted) .*",
    r"usb \d-\d+(\.\d:)?.*",
    r"systemd\[1\]: modprobe@.*\.service: Deactivated successfully\.",
    r"usb usb\d: .*",
    r"x86/fpu: xstate_offset\[\d+\]:\s*\d+, xstate_sizes\[\d+\]:\s*\d+",
    r"spi-nor spi0.1: .* \(4096 Kbytes\)",
    r"acpi/hmat: Locality: Flags:00 Type:(Read|Write) (Bandwidth|Latency) Initiator Domains:8 Target Domains:8 Base:100",
    r"mpt3sas[0-7]-msix0: PCI-MSI-X enabled: irq",
    r"node   [0-7]: \[mem HEX-HEX\]",
    r"pci_bus .*: (root bus )?resource (\d+ )?\[(mem|io)\s*HEX-HEX( window| 64bit pref)?\]",
    r"pci_bus .*: No. \d+ try to assign unassigned res",
    r"pci_bus .*: on NUMA node \d+",
    r"pci_bus .*: root bus resource \[bus [0-9a-f]+(-[0-9a-f]+)?\]",
    r"pci_bus .*: max bus depth: \d+ pci_try_num: \d+",
    r"pcieport .*: PME: Signaling with irq",
    r"pcieport ADDR: pciehp: Slot #\d+ AttnBtn- PwrCtrl- MRL- AttnInd- PwrInd- HotPlug\+ Surprise- Interlock- NoCompl\+ IbPresDis- LLActRep\+",
    r"i2c i2c-\d: 16/32 memory slots populated \(from DMI\)",
    r"i2c i2c-\d: Systems with more than 4 memory slots not supported yet, not instantiating SPD",
    r"perf: interrupt took too long \(.*\), lowering kernel\.perf_event_max_sample_rate to \d+",
    r"(eth0|veth): renamed from (veth|eth0)",
    r"veth: entered (promiscuous|allmulticast) mode",
    r"veth \(unregistering\): left (promiscuous|allmulticast) mode",
    r"(br|docker0): port \d+\(veth\) entered (disabled|blocking|forwarding) state",
    r"systemd\[\d+\]: memfd_create\(\) called without MFD_EXEC or MFD_NOEXEC_SEAL set",
    r"hugetlbfs: clusterkit \(\d+\): Using mlock ulimits for SHM_HUGETLB is obsolete",
    r"INFO: NMI handler \(.*\) took too long to run:",
    r"nvidia-nvswitch[0-7]: SXid \(PCI:ADDR\): \d+, (Non-fatal|Severity 0|Data).*",
    r"mlx5_core ADDR enp.*: Link up",
    r"mlx5_core ADDR enp.*: Link down",
    r"mlx5_core ADDR enp.*: renamed from eth\d",
    r"MFT device name created: id: \d+, slot id: \d+, device name: .*",
    r"hrtimer: interrupt took \d+ ns",
    r"workqueue: .* hogged CPU for .* consider switching to WQ_UNBOUND",
    r"ptrace attach of .* was attempted by .*",
    r"File /var/log/journal/.*.journal corrupted or uncleanly shut down, renaming and replacing.",
    r"usb-storage [\d\.:-]+ USB Mass Storage device detected",
    r"scsi HOST_NUM: usb-storage [\d\.:-]+",
    r".*Capabilities=\(.*",  # This line splits across lines weirdly sometimes,
    r".*,Task Set Full,NCQ\).*",  # This is also a part of the above
    r"systemd\[1\]: systemd 249.11-0ubuntu3.* running in system mode \(\+PAM \+AUDIT \+SELINUX \+APPARMOR \+IMA \+SMACK \+SECCOMP \+GCRYPT \+GNUTLS \+OPENSSL \+ACL \+BLKID \+CURL \+ELFUTILS \+FIDO2 \+IDN2 -IDN \+IPTC \+KMOD \+LIBCRYPTSETUP \+LIBFDISK \+PCRE2 -PWQUALITY -P11KIT -QRENCODE \+BZIP2 \+LZ4 \+XZ \+ZLIB \+ZSTD -XKBCOMMON \+UTMP \+SYSVINIT default-hierarchy=unified\)",
    r"input: DELL DRAC 5 Virtual Keyboard and Mouse as /devices/pci0000:00/ADDR/usb1/1-10/\d*-\d*\.\d*/\d*-\d*\.\d*:\d*\.\d*/\w*:\w*:\w*\.\w*/input/input.",
    r"hid-generic \w*:\w*:\w*\.\w*: input,hidraw.: USB HID v1\.01 (Mouse|Keyboard) \[DELL DRAC 5 Virtual Keyboard and Mouse\] on usb-ADDR-\w*\.\w*/input.",
    r"systemd-journald.*: File /var/log/journal/.*/system.journal corrupted or uncleanly shut down, renaming and replacing.",
    r"systemd-journald.*: File /var/log/journal/.*/user-1000.journal corrupted or uncleanly shut down, renaming and replacing.",
    r"systemd-journald.*: Failed to read journal file /var/log/journal/.*/user-1000.journal for rotation, trying to move it out of the way: Device or resource busy",
    r"sdID\[sda\] .* 512-byte logical blocks:",
    r"python\[.*\]: segfault at",
    r"python3\[.*\]: segfault at",
    r"pt_main_thread\[.*\]: segfault at",
    r"in python3.11\[.*\]",
    r"likely on CPU [0-9]",
    r"Code: [0-9a-f ]*",
    r"to colour dummy device",
    r"nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms",
    r"NVRM: loading NVIDIA UNIX x86_64 Kernel Module",
    r"Pid [0-9]*\(.*\) over core_pipe_limit",
    r"kauditd_printk_skb: \d+ callbacks suppressed",
]

WHITELISTED_MESSAGES = [
    "... bit width:              48",
    "... event mask:             0001000f000000ff",
    "... fixed-purpose events:   4",
    "... generic registers:      8",
    "... max period:             00007fffffffffff",
    "... value mask:             0000ffffffffffff",
    "... version:                5",
    ".... node  #",
    "..TIMER: vector=HEX apic1=0 pin1=2 apic2=-1 pin2=-1",
    "/init",
    "/usr/lib/systemd/system-generators/systemd-fstab-generator failed with exit status 1.",
    "00:04: ttyS1 at I/O HEX (irq = 3, base_baud = 115200) is a 16550A",
    "00:05: ttyS0 at I/O HEX (irq = 4, base_baud = 115200) is a 16550A",
    "63 BIT PCI BUS DMA ADDRESSING SUPPORTED, total mem",
    "ACPI Error: Aborting method \\_SB.PMI0._GHL due to previous error (AE_NOT_EXIST) (20230331/psparse-529)",
    "ACPI Error: Aborting method \\_SB.PMI0._PMC due to previous error (AE_NOT_EXIST) (20230331/psparse-529)",
    "ACPI Error: No handler for Region [SYSI]",
    "ACPI Error: Region IPMI (ID=7) has no handler (20230331/exfldio-261)",
    "ACPI FADT declares the system doesn't support PCIe ASPM, so disable it",
    "ACPI:",
    "AES CTR mode by8 optimization enabled",
    "AMD AuthenticAMD",
    "APIC: Switch to symmetric I/O mode setup",
    "AVX2 version of gcm_enc/dec engaged.",
    "Adding NUM_KB swap on /swap.img.",
    "AppArmor:",
    "Asymmetric key parser 'x509' registered",
    "BIOS-e820:",
    "BIOS-provided physical RAM map:",
    "BOOT_IMAGE=/boot/vmlinuz-6.5.0-1007-nvidia",
    "Backport based on mlnx_ofed/mlnx-ofa_kernel-4.0.git a675be0",
    "Block layer SCSI generic (bsg) driver version 0.4 loaded (major 243)",
    "Booting paravirtualized kernel on bare hardware",
    "Bridge firewalling registered",
    "Btrfs loaded, zoned=yes, fsverity=yes",
    "Built 8 zonelists, mobility grouping on.  Total pages: 264117399",
    "CPU_NUM: Thermal monitoring enabled (TM1)",
    "Calibrating delay loop (skipped), value calculated using timer frequency.. 4000.00 BogoMIPS (lpj=8000000)",
    "Centaur CentaurHauls",
    "Command line: BOOT_IMAGE=/boot/vmlinuz-6.5.0-1007-nvidia root=UUID=UUID ro",
    "Compat-mlnx-ofed backport release: a675be0",
    "Console:",
    'Creating 1 MTD partitions on "ADDR":',
    "DMA      [mem HEX-HEX]",
    "DMA32    [mem HEX-HEX]",
    "DMA:",
    "DMI: Dell Inc. PowerEdge SYSTEM_TAG, BIOS 1.3.6 09/20/2023",
    "DMI: Dell Inc. PowerEdge SYSTEM_TAG, BIOS 1.7.6 01/11/2024",
    "DMI: Dell Inc. PowerEdge SYSTEM_TAG, BIOS 1",
    "Dentry cache hash table entries: 33554432 (order: 16, 268435456 bytes, vmalloc hugepage)",
    "Device   empty",
    "Disabling lock debugging due to kernel taint",
    "Dynamic Preempt: voluntary",
    "EDAC MC",
    "EDAC MC: Ver: 3.0.0",
    "EDAC i10nm: No hbm memory",
    "EDAC i10nm: v0.0.6",
    "EISA bus registered",
    "ENERGY_PERF_BIAS: Set to 'normal', was 'performance'",
    "ERST: Error Record Serialization Table (ERST) support is initialized.",
    "EXT4-fs (NVMEn1p2): mounted filesystem UUID ro with ordered data mode. Quota mode: none.",
    "EXT4-fs (NVMEn1p2): re-mounted UUID r/w. Quota mode: none.",
    "Early memory node ranges",
    "Estimated ratio of average max frequency by base frequency (times 1024): 1638",
    "FS-Cache: Loaded",
    "Failed to create unit file /run/systemd/generator/mnt-nfs_clusterkit.mount",
    "Fallback order for Node",
    "Freeing SMP alternatives memory: 44K",
    "Freeing initrd memory: NUM_KB",
    "Freeing unused decrypted memory: 2036K",
    "Freeing unused kernel image (initmem) memory: 4792K",
    "Freeing unused kernel image (rodata/data gap) memory: 1156K",
    "GHES: APEI firmware first mode is enabled by APEI bit and WHEA _OSC.",
    "Giving out device to module i10nm_edac controller Intel_10nm Socket#0",
    "HEST: Table parsing has been initialized.",
    'HEX-HEX : "BIOS"',
    "HOME=/",
    "Hostname set to",
    "HugeTLB: 16380 KiB vmemmap can be freed for a 1.00 GiB page",
    "HugeTLB: 28 KiB vmemmap can be freed for a 2.00 MiB page",
    "HugeTLB: registered 1.00 GiB page size, pre-allocated 0 pages",
    "HugeTLB: registered 2.00 MiB page size, pre-allocated 0 pages",
    "Hygon HygonGenuine",
    "IOAPIC[0]: apic_id 8, version 32, address HEX, GSI 0-119",
    "IP idents hash table entries: 262144 (order: 9, 2097152 bytes, vmalloc)",
    "IPI shorthand broadcast: enabled",
    "IPMI message handler: version 39.2",
    "In-situ OAM (IOAM) with IPv6",
    "Initialise system trusted keyrings",
    "Initializing XFRM netlink socket",
    "Initmem setup",
    "Inode-cache hash table entries: 16777216 (order: 15, 134217728 bytes, vmalloc hugepage)",
    "Intel GenuineIntel",
    "KERNEL supported cpus:",
    "Kernel command line: BOOT_IMAGE=/boot/vmlinuz-6.5.0-1007-nvidia root=UUID=UUID ro",
    "LSM: initializing lsm=lockdown,capability,landlock,yama,apparmor,integrity",
    "Last level dTLB entries: 4KB 0, 2MB 0, 4MB 0, 1GB 0",
    "Last level iTLB entries: 4KB 0, 2MB 0, 4MB 0",
    "Linux agpgart interface v0.103",
    "Linux version 6.5.0-1007-nvidia (buildd@lcy02-amd64-008) (x86_64-linux-gnu-gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #7-Ubuntu SMP PREEMPT_DYNAMIC Wed Dec  6TIMEUTC 2023 (Ubuntu 6.5.0-1007.7-nvidia 6.5.3)",
    "Loaded X.509 cert",
    "Loading compiled-in X.509 certificates",
    "Loading compiled-in module X.509 certificates",
    "MPTCP token hash table entries: 65536 (order: 8, 1572864 bytes, vmalloc)",
    "MTRR map: 6 entries (3 fixed + 3 variable; max 23), built from 10 variable MTRRs",
    "Magic number:",
    "Memory: NUM_KB/NUM_KB available (NUM_KB kernel code, 4257K rwdata, NUM_KB rodata, 4792K init, NUM_KB bss, NUM_KB reserved, 0K cma-reserved)",
    "Monitor-Mwait will be used to enter C-1 state",
    "Mount-cache hash table entries: 524288 (order: 10, 4194304 bytes, vmalloc)",
    "Mountpoint-cache hash table entries: 524288 (order: 10, 4194304 bytes, vmalloc)",
    "Movable zone start for each node",
    "NET: Registered PF",
    "NFS: Registering the id_resolver key type",
    "NMI watchdog: Enabled. Permanently consumes one hw-PMU counter.",
    "NR_IRQS: 524544, nr_irqs: 2888, preallocated irqs: 16",
    "NUMA: Initialized distance table, cnt=8",
    "NUMA: Node 0 [mem HEX-HEX] + [mem HEX-HEX] -> [mem HEX-HEX]",
    "NVMEn1: p1 p2",
    "NVMEn1: p1 p9",
    "NVRM: loading NVIDIA UNIX x86_64 Kernel Module  535.129.03  Thu Oct 19TIMEUTC 2023",
    "NX (Execute Disable) protection: active",
    "NetLabel:  domain hash size = 128",
    "NetLabel:  protocols = UNLABELED CIPSOv4 CALIPSO",
    "NetLabel:  unlabeled traffic allowed by default",
    "NetLabel: Initializing",
    "No Arguments are initialized for method [_GHL]",
    "No Local Variables are initialized for Method [_GHL]",
    "Normal   [mem HEX-HEX]",
    "On node 0, zone DMA32: 10240 pages in unavailable ranges",
    "On node 0, zone DMA32: 46593 pages in unavailable ranges",
    "On node 0, zone DMA: 1 pages in unavailable ranges",
    "On node 0, zone DMA: 96 pages in unavailable ranges",
    "On node 0, zone Normal: 2048 pages in unavailable ranges",
    "PCI host bridge to bus",
    "PCI-DMA: Using software bounce buffering for IO (SWIOTLB)",
    "PCI: CLS 0 bytes, default 64",
    "PCI: Dell System detected, enabling pci=bfsort.",
    "PCI: Ignoring E820 reservations for host bridge windows",
    "PCI: MMCONFIG at [mem HEX-HEX] reserved as EfiMemoryMappedIO",
    "PCI: MMCONFIG for domain 0000 [bus 00-ff] at [mem HEX-HEX] (base HEX)",
    "PCI: Using ACPI for IRQ routing",
    "PCI: Using configuration type 1 for base access",
    'PCI: Using host bridge windows from ACPI; if necessary, use "pci=nocrs" and report a bug',
    "PCI: not using MMCONFIG",
    "PCI: pci_cache_line_size set to 64 bytes",
    "PM: RTC time:TIME date: DATE",
    "PM: hibernation: Registered nosave memory: [mem",
    "PPP generic driver version 2.4.2",
    "PTP clock support registered",
    "Performance Events: XSAVE Architectural LBR, PEBS fmt4+-baseline,  AnyThread deprecated, Sapphire Rapids events, 32-deep LBR, full-width counters, Intel PMU driver.",
    "Policy zone: Normal",
    "Process accounting resumed",
    "Protocol=(Initiator), Capabilities=(Diag Trace Buffer,Task Set Full,NCQ)",
    "RAMDISK: [mem HEX-HEX]",
    "RAPL PMU: API unit is 2^-32 Joules, 3 fixed counters, 655360 ms ovfl timer",
    "RAPL PMU: hw unit of domain dram 2^-14 Joules",
    "RAPL PMU: hw unit of domain package 2^-14 Joules",
    "RAPL PMU: hw unit of domain psys 2^-0 Joules",
    "RAS: Correctable Errors collector initialized.",
    "RCU Tasks Rude: Setting shift to 7 and lim to 1 rcu_task_cb_adjust=1.",
    "RCU Tasks Trace: Setting shift to 7 and lim to 1 rcu_task_cb_adjust=1.",
    "RCU Tasks: Setting shift to 7 and lim to 1 rcu_task_cb_adjust=1.",
    "RPC: Registered named UNIX socket transport module.",
    "RPC: Registered tcp NFSv4.1 backchannel transport module.",
    "RPC: Registered tcp transport module.",
    "RPC: Registered tcp-with-tls transport module.",
    "RPC: Registered udp transport module.",
    "Received client request to flush runtime journal.",
    "Rude variant of Tasks RCU enabled.",
    "Run /init as init process",
    "SCSI subsystem initialized",
    "SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=104, Nodes=8",
    "SMBIOS 3.3.0 present.",
    "Segment Routing with IPv6",
    "Serial: 8250/16550 driver, 32 ports, IRQ sharing enabled",
    "Shutdown timeout set to",
    "Spectre V1 : Mitigation: usercopy/swapgs barriers and __user pointer sanitization",
    "Spectre V2 : Mitigation: Enhanced / Automatic IBRS",
    "Spectre V2 : Spectre v2 / PBRSB-eIBRS: Retire a single CALL on VMEXIT",
    "Spectre V2 : Spectre v2 / SpectreRSB mitigation: Filling RSB on context switch",
    "Spectre V2 : mitigation: Enabling conditional Indirect Branch Prediction Barrier",
    "Speculative Store Bypass: Mitigation: Speculative Store Bypass disabled via prctl",
    "Switched APIC routing to physical flat.",
    "TCP bind hash table entries: 65536 (order: 9, 2097152 bytes, vmalloc)",
    "TCP established hash table entries: 524288 (order: 10, 4194304 bytes, vmalloc)",
    "TCP: Hash tables configured (established 524288 bind 65536)",
    "TERM=linux",
    "TSC deadline timer available",
    "Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, vmalloc)",
    "Tracing variant of Tasks RCU enabled.",
    "Trampoline variant of Tasks RCU enabled.",
    "Trying to unpack rootfs image as initramfs...",
    "UDP hash table entries: 65536 (order: 9, 2097152 bytes, vmalloc)",
    "UDP-Lite hash table entries: 65536 (order: 9, 2097152 bytes, vmalloc)",
    'Unknown kernel command line parameters "BOOT_IMAGE=/boot/vmlinuz-6.5.0-1007-nvidia", will be passed to user space.',
    "Using GB pages for direct mapping",
    "VFIO - User Level meta-driver version: 0.3",
    "VFS: Disk quotas dquot_6.6.0",
    "VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)",
    "Write protecting the kernel read-only data: NUM_KB",
    "Yama: becoming mindful.",
    "ZFS: Loaded module v2.2.0-0ubuntu1~23.10, ZFS pool version 5000, ZFS filesystem version 5",
    "Zone ranges:",
    "[Firmware Info]: PCI: MMCONFIG at [mem HEX-HEX] not reserved in ACPI motherboard resources",
    "[drm] Initialized mgag200 1.0.0 20110418 for ADDR on minor 0",
    "[drm] Initialized nvidia-drm 0.0.0 20160202 for ADDR on minor",
    "[drm] [nvidia-drm] [GPU ID HEX] Loading driver",
    "[mem HEX-HEX] available for PCI devices",
    "acpi PNP0A03",
    "acpi PNP0A08",
    "acpi/hmat:   Initiator-Target",
    "acpi/hmat: Memory Flags:0001 Processor Domain:",
    "acpiphp: ACPI Hot Plug PCI Controller Driver version: 0.5",
    "ahci ADDR: AHCI 0001.0301 32 slots 4 ports 6 Gbps HEX impl SATA mode",
    "ahci ADDR: flags: 64bit ncq sntf pm clo only pio slum part ems deso sadm sds",
    "ahci ADDR: version 3.0",
    "alua: device handler registered",
    "async_tx: api initialized (async)",
    "audit: initializing netlink subsys (disabled)",
    'audit: type=1400 TIME: apparmor="STATUS" ',
    "audit: type=2000 TIME: state=initialized audit_enabled=0 res=1",
    'audit: type=1400 TIME: apparmor="DENIED"',
    "blacklist: Loading compiled-in revocation X.509 certificates",
    "blacklist: Revoked X.509 cert 'Debian Secure Boot Signer: 00a7468def'",
    "block NVMEn1: the capability attribute has been deprecated.",
    "bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.",
    "clk: Disabling unused clocks",
    "clocksource:",
    "compat.git: mlnx_ofed/mlnx-ofa_kernel-4.0.git",
    "cpuidle: using governor ladder",
    "cpuidle: using governor menu",
    "cryptd: max_cpu_qlen set to 1000",
    "dcdbas dcdbas: Dell Systems Management Base Driver (version 5.6.0-3.4)",
    "device-mapper: core: CONFIG_IMA_DISABLE_HTABLE is disabled. Duplicate IMA measurements will not be recorded in the IMA log.",
    "device-mapper: ioctl: 4.48.0-ioctl (DATE) initialised: dm-devel@redhat.com",
    "device-mapper: uevent: version 1.0.3",
    "devtmpfs: initialized",
    "drop_monitor: Initializing network drop monitor service",
    "e820: remove [mem HEX-HEX] reserved",
    "e820: remove [mem HEX-HEX] usable",
    "e820: reserve RAM buffer [mem HEX-HEX]",
    "e820: update [mem HEX-HEX] usable ==> reserved",
    "e820: update [mem HEX-HEX] usable ==> usable",
    "efi: ACPI=HEX ACPI 2.0=HEX MEMATTR=HEX SMBIOS=HEX SMBIOS 3.0=HEX MOKvar=HEX RNG=HEX",
    "efi: EFI v2.7 by Dell Inc.",
    "efi: Not removing MEM_ADDR: MMIO range=[HEX-HEX] (4KB) from e820 map",
    "efi: Remove MEM_ADDR: MMIO range=[HEX-HEX] (256MB) from e820 map",
    "efifb: No BGRT, not showing boot graphics",
    "efifb: Truecolor: size=8:8:8:8, shift=24:16:8:0",
    "efifb: framebuffer at HEX, using 3072k, total 3072k",
    "efifb: mode is 1024x768x32, linelength=4096, pages=1",
    "efifb: probing for efifb",
    "efifb: scrolling: redraw",
    "efivars: Registered efivars operations",
    "emc: device handler registered",
    "end_DEVICE add: handle(HEX), sas_addr(HEX)",
    "evict_inodes",
    "evm: HMAC attrs: HEX",
    "evm: Initialising EVM extended attributes:",
    "evm: security.",
    "extended physical RAM map:",
    "fb0: EFI VGA frame buffer device",
    "fbcon: Taking over console",
    "fbcon: mgag200drmfb (fb0) is primary device",
    "ftrace: allocated 216 pages with 4 groups",
    "ftrace: allocating 55296 entries in 216 pages",
    "fuse: init (API version 7.38)",
    "futex hash table entries: 32768 (order: 9, 2097152 bytes, vmalloc)",
    "hash matches",
    "hpet0: 8 comparators, 64-bit 25.000000 MHz counter",
    "hpet0: at MMIO HEX, IRQs 2, 8, 0, 0, 0, 0, 0, 0",
    "i2c i2c-1: 16/32 memory slots populated (from DMI)",
    "i2c i2c-1: Systems with more than 4 memory slots not supported yet, not instantiating SPD",
    "i2c_dev: i2c /dev entries driver",
    "i801_smbus ADDR: SMBus using PCI interrupt",
    "i801_smbus ADDR: SPD Write Disable is set",
    "i8042: PNP: No PS/2 controller found.",
    "idxd ADDR: Intel(R) Accelerator Device (v100)",
    "idxd ADDR: Unable to turn on user SVA feature.",
    "ima: Allocated hash algorithm: sha1",
    "ima: No TPM chip found, activating TPM-bypass!",
    "ima: No architecture policies found",
    "input: Power Button as /devices/LNXSYSTM:00/LNXPWRBN:00/input/input1",
    "input: Power Button as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input0",
    "integrity: Loaded X.509 cert",
    "integrity: Loading X.509 certificate",
    "integrity: Machine keyring initialized",
    "integrity: Platform Keyring initialized",
    "integrity: Revoking X.509 certificate: UEFI:dbx",
    "intel_pstate: Intel P-state driver initializing",
    "intel_rapl_common: Found RAPL domain",
    "io scheduler mq-deadline registered",
    "iommu: DMA domain TLB invalidation policy: lazy mode",
    "iommu: Default domain type: Translated",
    "ipmi device interface",
    "ipmi_platform: ipmi_si: SMBIOS: io HEX regsize 1 spacing 4 irq",
    "ipmi_si IPI0001:00: IPMI kcs interface initialized",
    "ipmi_si IPI0001:00: IPMI message handler: Found new BMC (man_id: HEX, prod_id: HEX, dev_id: HEX)",
    "ipmi_si IPI0001:00: The BMC does not support setting the recv irq bit, compensating, but the BMC needs to be fixed.",
    "ipmi_si IPI0001:00: Using irq",
    "ipmi_si IPI0001:00: ipmi_platform: [io  HEX] regsize 1 spacing 4 irq",
    "ipmi_si IPI0001:00: ipmi_platform: probing via ACPI",
    "ipmi_si dmi-ipmi-si.0: Removing SMBIOS-specified kcs state machine in favor of ACPI",
    "ipmi_si dmi-ipmi-si.0: ipmi_platform: probing via SMBIOS",
    "ipmi_si: Adding ACPI-specified kcs state machine",
    "ipmi_si: Adding SMBIOS-specified kcs state machine",
    "ipmi_si: IPMI System Interface driver",
    "ipmi_si: Trying ACPI-specified kcs state machine at i/o address HEX, slave address HEX, irq",
    "ipmi_ssif: IPMI SSIF Interface driver",
    "is added to hba_port list",
    "knem 1.1.4.90mlnx3: initialized",
    "kprobes: kprobe jump-optimization is enabled. All kprobes are optimized if possible.",
    "landlock: Up and running.",
    "last_pfn = HEX max_arch_pfn = HEX",
    "ledtrig-cpu: registered to indicate activity on CPUs",
    "libata version 3.00 loaded.",
    "loop: module loaded",
    "mctp: management component transport protocol core",
    "mei_me ADDR: Device doesn't have valid ME Interface",
    "mem auto-init: stack:off, heap alloc:on, heap free:off",
    "mempolicy: Enabling automatic NUMA balancing. Configure with numa_balancing= or the kernel.numa_balancing sysctl",
    "mf:",
    "mgag200 ADDR: [drm] fb0: mgag200drmfb frame buffer device",
    "mgag200 ADDR: vgaarb: deactivate vga console",
    "microcode: Microcode Update Driver: v2.2.",
    "microcode: updated early: HEX -> HEX, date = DATE",
    "mlx5_core : mlx5_pcie_event:299:(PID): Detected insufficient power on the PCIe slot (27W).",
    "mlx5_core ADDR: 252.048 Gb/s available PCIe bandwidth (16.0 GT/s PCIe x16 link)",
    "mlx5_core ADDR: E-Switch: Total vports 2, per vport: max uc(128) max mc(2048)",
    "mlx5_core ADDR: MLX5E: StrdRq(1) RqSz(8) StrdSz(2048) RxCqeCmprss(0 enhanced)",
    "mlx5_core ADDR: Port module event: module 0, Cable plugged",
    "mlx5_core ADDR: Port module event: module 1, Cable unplugged",
    "mlx5_core ADDR: Rate limit: 127 rates are supported, range: 0Mbps to 97656Mbps",
    "mlx5_core ADDR: firmware version: 22.36.1010",
    "mlx5_core ADDR: firmware version: 28.39.1002",
    "mlx5_core ADDR: mlx5_pcie_event:299:(PID): Detected insufficient power on the PCIe slot (27W).",
    "mlx5_core ADDR: mlx5_pcie_event:299:(PID): Detected insufficient power on the PCIe slot ADDR(27W).",
    "mlx_compat: loading out-of-tree module taints kernel.",
    "mlx_compat: module verification failed: signature and/or required key missing - tainting kernel",
    "mousedev: PS/2 mouse device common for all mice",
    "mpt3sas version 43.100.00.00 loaded",
    'mtd: partition "BIOS" extends beyond the end of device "ADDR" -- size truncated to HEX',
    "mtrr_cleanup: can not find optimal value",
    "no of cores: 104, max_msix_vectors: -1",
    "nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  535.129.03  Thu Oct 19TIMEUTC 2023",
    "nvidia-nvlink: Nvlink Core is being initialized, major device number 237",
    "nvidia-nvlink: nvlink driver close",
    "nvidia-nvlink: nvlink driver open",
    "nvidia-nvswitch0: open (major=236)",
    "nvidia-nvswitch0: using MSI",
    "nvidia-nvswitch1: open (major=236)",
    "nvidia-nvswitch1: using MSI",
    "nvidia-nvswitch2: open (major=236)",
    "nvidia-nvswitch2: using MSI",
    "nvidia-nvswitch3: open (major=236)",
    "nvidia-nvswitch3: using MSI",
    "nvidia-nvswitch: Probing device ADDR, Vendor Id = HEX, Device Id = HEX, Class = HEX",
    "nvidia-uvm: Loaded the UVM driver, major device number 235.",
    "nvidia: module license 'NVIDIA' taints kernel.",
    "nvidia: module license taints kernel.",
    "nvidia_uvm: module uses symbols nvUvmInterfaceDisableAccessCntr from proprietary module nvidia, inheriting taint.",
    "nvme NVME: 104/0/0 default/read/poll queues",
    "nvme NVME: 3/0/0 default/read/poll queues",
    "nvme NVME: pci function ADDR",
    "pci_bus 0000:04: extended config space not accessible",
    "pci_bus 0000:80: Some PCI device resources are unassigned, try booting with pci=realloc",
    "pcpu-alloc:",
    "percpu: Embedded 63 pages/cpu s221184 r8192 d28672 u262144",
    "pid_max: default: 106496 minimum: 832",
    "pinctrl core: initialized pinctrl subsystem",
    "platform eisa.0: Cannot allocate resource for EISA slot",
    "platform eisa.0: EISA: Cannot allocate resource for mainboard",
    "platform eisa.0: EISA: Detected 0 cards",
    "platform eisa.0: Probing EISA bus 0",
    "please specify mtrr_gran_size/mtrr_chunk_size",
    "pnp 00:01: disabling [mem HEX-HEX disabled] because it overlaps ADDR BAR 8 [mem HEX-HEX 64bit pref]",
    "pnp 00:01: disabling [mem HEX-HEX] because it overlaps ADDR BAR 8 [mem HEX-HEX 64bit pref]",
    "pnp 00:02: disabling [mem HEX-HEX disabled] because it overlaps ADDR BAR 8 [mem HEX-HEX 64bit pref]",
    "pnp 00:02: disabling [mem HEX-HEX] because it overlaps ADDR BAR 8 [mem HEX-HEX 64bit pref]",
    "pnp: PnP ACPI init",
    "pnp: PnP ACPI: found 6 devices",
    "pps_core: LinuxPPS API ver. 1 registered",
    "pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>",
    "printk: console [tty0] enabled",
    "printk: early log buf free:",
    "printk: log_buf_len",
    "process: using mwait in idle threads",
    "pstore: Registered erst as persistent store backend",
    "pstore: Using crash dump compression: deflate",
    "pstore: backend 'erst' already in use: ignoring 'efi_pstore'",
    "raid6: .... xor() MB_S, rmw enabled",
    "raid6: avx2x1   gen() MB_S",
    "raid6: avx2x2   gen() MB_S",
    "raid6: avx2x4   gen() MB_S",
    "raid6: avx512x1 gen() MB_S",
    "raid6: avx512x2 gen() MB_S",
    "raid6: avx512x4 gen() MB_S",
    "raid6: using algorithm avx512x2 gen() MB_S",
    "raid6: using avx512x2 recovery algorithm",
    "random: crng init done",
    "rcu: \tMax phase no-delay instances is 1000.",
    "rcu: \tRCU restricting CPUs from NR_CPUS=8192 to nr_cpu_ids=104.",
    "rcu:         Max phase no-delay instances is 1000.",
    "rcu:         RCU restricting CPUs from NR_CPUS=8192 to nr_cpu_ids=104.",
    "rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=104",
    "rcu: Hierarchical SRCU implementation.",
    "rcu: Preemptible hierarchical RCU implementation.",
    "rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.",
    "rcu: srcu_init: Setting srcu_struct sizes based on contention.",
    "rdac: device handler registered",
    "registered taskstats version 1",
    "release child resource [mem HEX-HEX 64bit pref]",
    "release child resource [mem HEX-HEX 64bit]",
    "resctrl: L2 allocation detected",
    "resctrl: L3 allocation detected",
    "resctrl: L3 monitoring detected",
    "resctrl: MB allocation detected",
    "reserve setup_data: [mem HEX-HEX] ACPI NVS",
    "reserve setup_data: [mem HEX-HEX] ACPI data",
    "reserve setup_data: [mem HEX-HEX] reserved",
    "reserve setup_data: [mem HEX-HEX] usable",
    "rtc_cmos 00:00: RTC can wake from S4",
    "rtc_cmos 00:00: alarms up to one month, y3k, 114 bytes nvram",
    "rtc_cmos 00:00: registered as rtc0",
    "sched_clock: Marking stable",
    "scsi HOST_NUM: Fusion MPT SAS Host",
    "scsi HOST_NUM: ahci",
    "scsiIDAttached scsi generic sg type 13",
    "scsiIDEnclosure         Dell     Fryer U.2 (SW1)  00   PQ: 0 ANSI: 5",
    "scsiIDEnclosure         Dell     Fryer U.2 (SW1)  00   PQ: 0 ANSI: 5",
    "scsiIDEnclosure         Dell     Fryer U.2 (SW2)  00   PQ: 0 ANSI: 5",
    "scsiIDEnclosure         Dell     Fryer U.2 (SW3)  00   PQ: 0 ANSI: 5",
    "scsiIDEnclosure         Dell     Fryer U.2 (SW4)  00   PQ: 0 ANSI: 5",
    "scsiIDPower-on or device reset occurred",
    "scsiIDSES: handle(HEX), sas_addr(HEX), phy(0), device_name(HEX)",
    "scsiIDenclosure logical id (HEX), slot(0)",
    "scsiIDqdepth(3), tagged(1), scsi_level(6), cmd_que(1)",
    "scsiIDset ignore_delay_remove for handle(HEX)",
    "sdIDAttached scsi generic sg type",
    "secureboot: Secure boot disabled",
    "sesIDAttached Enclosure device",
    "setting system clock to",
    "setup_percpu: NR_CPUS:8192 nr_cpumask_bits:104 nr_cpu_ids:104 nr_node_ids:8",
    "shpchp: Standard Hot Plug PCI Controller Driver version: 0.4",
    "signal: max sigframe size: 11952",
    "smp: Bringing up secondary CPUs ...",
    "smp: Brought up 8 nodes, 104 CPUs",
    "smpboot: Allowing 104 CPUs, 0 hotplug CPUs",
    "smpboot: CPU 52 Converting physical 0 to logical die 1",
    "smpboot: CPU_NUM: Intel(R) Xeon(R) Platinum 8470 (family: HEX, model: HEX, stepping: HEX)",
    "smpboot: Max logical packages: 2",
    "smpboot: Total of 104 processors activated (416000.00 BogoMIPS)",
    "smpboot: x86: Booting SMP configuration:",
    "software IO TLB: area num 128.",
    "software IO TLB: mapped [mem HEX-HEX] (64MB)",
    "spi-nor spi0.0: mx25u25635f (32768 Kbytes)",
    "spi-nor: probe of spi0.1 failed with error -524",
    "squashfs: version 4.0 (2009/01/31) Phillip Lougher",
    "switchtec switchtec0: Management device registered.",
    "switchtec: loaded.",
    "system 00:01: [io  HEX-HEX] has been reserved",
    "system 00:02: [io  HEX-HEX] has been reserved",
    "systemd[1]: Activated swap /swap.img.",
    "systemd[1]: Activating swap /swap.img...",
    "systemd[1]: Condition check resulted in File System Check on Root Device being skipped.",
    "systemd[1]: Condition check resulted in First Boot Complete being skipped.",
    "systemd[1]: Condition check resulted in Kernel Module supporting RPCSEC_GSS being skipped.",
    "systemd[1]: Condition check resulted in LXD - agent being skipped.",
    "systemd[1]: Condition check resulted in OpenVSwitch configuration for cleanup being skipped.",
    "systemd[1]: Condition check resulted in Platform Persistent Storage Archival being skipped.",
    "systemd[1]: Detected architecture x86-64.",
    "systemd[1]: Inserted module 'autofs4'",
    "systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.",
    "systemd[1]: modprobe@configfs.service: Deactivated successfully.",
    "systemd[1]: modprobe@drm.service: Deactivated successfully.",
    "systemd[1]: modprobe@efi_pstore.service: Deactivated successfully.",
    "systemd[1]: modprobe@fuse.service: Deactivated successfully.",
    "systemd[1]: systemd 249.11-0ubuntu3.11 running in system mode (+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)",
    "systemd[1]: systemd 249.11-0ubuntu3.7 running in system mode (+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)",
    "tcp_listen_portaddr_hash hash table entries: 65536 (order: 8, 1048576 bytes, vmalloc)",
    "tg3 ADDR eno8303: renamed from eth0",
    "tg3 ADDR eno8403: renamed from eth1",
    "tg3 ADDR eth0: RXcsums[1] LinkChgREG[0] MIirq[0] ASF[1] TSOcap[1]",
    "tg3 ADDR eth0: Tigon3 [partno(BCM95720) rev 5720000] (PCI Express) MAC",
    "tg3 ADDR eth0: attached PHY is 5720C (10/100/1000Base-T Ethernet) (WireSpeed[1], EEE[1])",
    "tg3 ADDR eth0: dma_rwctrl[00000001] dma_mask[64-bit]",
    "tg3 ADDR eth1: RXcsums[1] LinkChgREG[0] MIirq[0] ASF[1] TSOcap[1]",
    "tg3 ADDR eth1: Tigon3 [partno(BCM95720) rev 5720000] (PCI Express) MAC",
    "tg3 ADDR eth1: attached PHY is 5720C (10/100/1000Base-T Ethernet) (WireSpeed[1], EEE[1])",
    "tg3 ADDR eth1: dma_rwctrl[00000001] dma_mask[64-bit]",
    "thermal_sys: Registered thermal governor",
    "total RAM covered: 2095104M",
    "tsc: Detected 2000.000 MHz processor",
    "tun: Universal TUN/TAP device driver, 1.6",
    "usb: port power management may be unreliable",
    "usbcore:",
    "vgaarb: loaded",
    "with arguments:",
    "with environment:",
    "wmi_bus wmi_bus-PNP0C14:01: WQBC data block query control method not found",
    "workingset: timestamp_bits=36 max_order=28 bucket_order=0",
    "workqueue: work_for_cpu_fn",
    "x2apic: IRQ remapping doesn't support X2APIC mode",
    "x86/PAT: Configuration [0-7]: WB  WC  UC- UC  WB  WP  UC- WT",
    "x86/cpu: SGX disabled by BIOS.",
    "x86/cpu: User Mode Instruction Prevention (UMIP) activated",
    "x86/cpu: VMX (outside TXT) disabled by BIOS",
    "x86/fpu: Enabled xstate features HEX, context size is 10752 bytes, using 'compacted' format.",
    "x86/fpu: Supporting XSAVE feature HEX:",
    "x86/mm: Checked W+X mappings: passed, no W+X pages found.",
    "x86/mm: Memory block size: 2048MB",
    "x86/split lock detection: #AC: crashing the kernel on kernel split_locks and warning on user-space split_locks",
    "x86/tme: not enabled by BIOS",
    "xhci_hcd ADDR: Host supports USB 3.1 Enhanced SuperSpeed",
    "xhci_hcd ADDR: hcc params HEX hci version HEX quirks HEX",
    "xhci_hcd ADDR: new USB bus registered, assigned bus number 1",
    "xhci_hcd ADDR: new USB bus registered, assigned bus number 2",
    "xhci_hcd ADDR: xHCI Host Controller",
    "xor: automatically using best checksumming function   avx",
    "zbud: loaded",
    "zhaoxin   Shanghai",
    "evict_inodes",
    "nvidia-peermem nv_get_p2p_free_callback:125 ERROR detected invalid context, skipping further processing",
    "mlx5_core ADDR: Port module event: module 0, Cable unplugged",
    "Cannot map memory with base addr HEX and size of HEX pages",
    "Received SIGTERM from PID 1 (systemd)",
    "process `grep' is using deprecated sysctl",
    "hid: raw HID events driver (C) Jiri Kosina",
    "usbhid: USB HID core driver",
    "scsiIDDirect-Access     Linux    RACADM           0001 PQ: 0 ANSI: 0",
    "scsiIDDirect-Access     Linux    SECUPD           0001 PQ: 0 ANSI: 0",
    "sdIDPower-on or device reset occurred",
    "sdID[sda] Write Protect is off",
    "sdID[sda] Mode Sense: 23 00 00 00",
    "sdID[sda] No Caching mode page found",
    "sdID[sda] Mode Sense: 45 00 00 00",
    "sdID[sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA",
    "sdID[sda] Assuming drive cache: write through",
    "sda: sda1",
    "sdID[sda] Attached SCSI removable disk",
    "nvidia-uvm: Loaded the UVM driver, major device number",
    "scsiIDDirect-Access     PNY      USB 2.0 FD       PMAP PQ: 0 ANSI: 6",
    "nfs: server 10.0.96.201",
    "Skipping core dump",
]

# A mapping from initial message to a termination message
# All messages between the initial and termination message should be whitelisted
WHITELISTED_MESSAGE_RANGES = {"invoked oom-killer: gfp_mask=": "oom_reaper: reaped process"}

# The set of all SXid error ids that are known to be harmless.
# See D.4 of https://docs.nvidia.com/datacenter/tesla/pdf/fabric-manager-user-guide.pdf
WHITELISTED_NVSWITCH_SXID_ERRORS = [
    "11012",
    "11021",
    "11022",
    "11023",
    "12021",
    "12023",
    "15008",
    "15011",
    "19049",
    "19055",
    "19057",
    "19059",
    "19062",
    "19065",
    "19068",
    "19071",
    "24001",
    "24002",
    "24003",
    "22013",
]
